# Generated by Django 5.0 on 2023-12-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_booking_date_reservation_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='created',
            new_name='booking_date',
        ),
    ]
